export const layout = {
  screenPadding: 16,
  sectionTitleTopPadding: 80,
  sectionTitleFontSize: 18,
  headerTopPadding: 32,
  headerBottomPadding: 18,
  floatingCardRadius: 18,
  floatingHorizontal: 16,
  carouselSeparator: 12,
  carouselItemWidth: 160,
  resultsThumbWidth: 160,
  resultsThumbHeight: 213,
  resultsSpacerOffset: 130,
  heroHeight: 220,
} as const;
