export const strings = {
  hello: 'Olá,',
  userName: 'Monica!',
  seeMore: 'Ver mais',
  seeMoreArrow: '›',
  newsForYou: 'Novidades para você!',
  results: 'Resultados',
  errorLoading: 'Falha ao carregar dados',
  home: 'Página inicial',
  identity: 'Identidade',
  care: 'Cuidados',
  regeneration: 'Regeneração',
  maintenance: 'Manutenção',
  checkups: 'Checkups',
  trail: 'Trilha',
  messages: 'Mensagens',
  empty: 'Sem mensagens',
  mediaSeeProgress: 'Veja sua evolução',
  modalPrimaryDownload: 'Arquivo.pdf',
  modalDefaultTitle: 'Detalhes',
  modalDetailsTemplate: (title: string, date: string, status: string) =>
    `Detalhes sobre: ${title}\n\nData: ${date}\nStatus: ${status}\n\nEste é um exemplo de conteúdo detalhado para o procedimento.`,
  a11yBack: 'Voltar',
  a11yShare: 'Compartilhar',
  a11yMessages: 'Mensagens',
  a11yProfile: 'Perfil',
} as const;
